### PR TITLE
Normalize line endings

### PR DESCRIPTION
**Pull request by bethmaloney**
Normalise line endings and enable `autocrlf`. This should result in all files ending in CRLF in windows and LF in Linux (and Git). This will resolve the warnings in VS about inconsistent line endings.

I've opened this PR based on the conversation at https://github.com/nhibernate/fluent-nhibernate/pull/641. I'll keep both PRs open for now and when one approach is selected I'll close the other PR.

### CODE REVIEW

**Comment by oskarb** [comment]
For what it's worth, I support this change. As I mentioned in the other PR, my experience from multiple projects for many years is that this works well.

Additionally, this PR has been executed in a good way - by that I mean that it contains *only* the line ending changes (apart from the gitattributes file of course), meaning that it is easy to verify using diff that it doesn't try to sneak in any behaviour changes.

**Comment by hazzik** [comment]
Thanks

**Comment by hazzik** [comment]
I think this would conflict with .editorconfig file:
https://github.com/nhibernate/fluent-nhibernate/blob/6c8df8535225cfcff7c95d05d6811a941611c61d/.editorconfig#L6-L7

**Comment by bethmaloney** [comment]
@hazzik Thanks! I've removed that line from the editorconfig and also updated the contributing guidelines to remove references to disabling autocrlf

**Pull request merged**
