### PR TITLE
Update ClasslikeMapBase.cs

### PR DESCRIPTION
**Pull request by mgpx**
For when you want to make a custom map class.

### CODE REVIEW

**Comment by mgpx** [comment]
Example:
```
using FluentNHibernate;
using FluentNHibernate.Mapping;
using System;
using System.Linq;
using System.Reflection;

namespace Example
{
    public class AutoClassMap<T> : ClassMap<T>
    {
        private Type type = null;
        
        public AutoClassMap()
        {
            type = typeof(T);
            RunMap();
        }

        protected void RunMap()
        {
	     //..
            var mapNormal = type.GetProperties().Where(prop => Attribute.IsDefined(prop, typeof(MapNormalAttribute)));
            
            foreach(PropertyInfo item in mapNormal)
            {
                String columnName = item.Name.ToLower();

		//manipulate items
		columnName = "Prefix_" + columnName; 
                var member = item.ToMember();

		//call method protected 
                base.Map(member, columnName);
            }
			
	     //...
        }
    }
    
    [AttributeUsage(AttributeTargets.Property, Inherited = false)]
    public class MapNormalAttribute : Attribute
    {

    }
}
````

**Comment by jrgcubano** [comment]
@mgpx Thank you for your PR. 

First, You have taken a look at AutoMapping [AutoMapping](https://github.com/FluentNHibernate/fluent-nhibernate/wiki/Auto-mapping) with some convention?

**Comment by mgpx** [comment]
Is that here in the company has some patterns, for example each table, has a prefix of its own in the columns

```
Product Table:

prod_id
prod_name

Users Table:
user_id
user_name
```



Currently I did with reflection, but I thought that someone else could go through this, for that reason I did the PR.

```
methodInfoMap = typeof(ClasslikeMapBase<>).MakeGenericType(typeof(T)).GetMethod("Map", BindingFlags.NonPublic | BindingFlags.Instance);
methodInfoMap.Invoke(this, new Object[] { member, columnName });

```

**Comment by hazzik** [comment]
This should be doable with conventions.

**Pull request closed without merging**
